### ISSUE TITLE
micropub article JATS format - can't be read into xml

### ISSUE THREAD

**Issue by kyook** [bioentity/papers#851]
This file (as .xml, could not be read into DMC)
[tsialikas_jats.txt](https://github.com/bioentity/papers/files/2120661/tsialikas_jats.txt)

**Comment by nickstiffler** [comment]
I add an exception and was able to import it using the elife ingester. It checks the journal name, so it is checking for "micropublication" now.

**Comment by kyook** [comment]
If I wanted to import PLoS articles, will I need to add this name to the list?  Would you point me to the script lines to add exceptions for other journal articles?

**Comment by kyook** [comment]
have the changes that allow this micropub article pulled into production yet?

**Comment by kyook** [comment]
yes, I keep forgetting.
